### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [MindsHub/insigno_frontend#10]
~~...since it's not reproducible~~

~~ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/5215633867#L958~~

~~/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/4da6ce6e2a8a41bd77a8767820f1535caa535cee~~

/LE2: oh wait a bit... see below

**Comment by licaon-kter** [comment]
My bad, no notes were available so I was trying to fix a fixed issue :facepalm: 

Added note now: https://gitlab.com/fdroid/fdroiddata/-/commit/b71061f75fd20f3a51bcf6dd0bc39e02c1d8a4a1

Sorry for the noise

**Comment by Stypox** [comment]
Sorry for the confusion. Should I open a MR on fdroiddata to force the CI to build in the same folder as the fdroid build system, i.e. `/home/vagrant/build/org.mindshub.insigno`?

**Comment by licaon-kter** [comment]
@Stypox yes and no

We usually have a folder move that mimics what upstream has and that is consistent in CI and build server:
```
    sudo:
      - mkdir -p /home/runner/
      - chown vagrant /home/runner/
    prebuild:
      - export repo=/home/runner/work/SomeName
      - mkdir -p $repo
      - cd ..
      - mv appid $repo/SomeName
      - pushd $repo/SomeName
      - export PUB_CACHE=$(pwd)/.pub-cache
      - $$flutter$$/bin/flutter config --no-analytics
      - $$flutter$$/bin/flutter pub get
      - popd
      - mv $repo/SomeName appid
      - cd appid
    build:
      - export repo=/home/runner/work/SomeName
      - cd ..
      - mv appid $repo/SomeName
      - pushd $repo/SomeName
      - export PUB_CACHE=$(pwd)/.pub-cache
      - $$flutter$$/bin/flutter build apk
      - popd
      - mv $repo/SomeName appid
```
...no idea on the timing, if such recipe was invented after your app/CI was setup
